language: node_js
node_js:
  - 'node'
cache: yarn
jobs:
  include:
    - stage: test
      script: yarn test --coverage
      after_success: 'yarn coveralls'
    - stage: build
      script: yarn build
